# library = [
#     {"title": "1984", "author": "George Orwell", "year": 1949, "genre": "Dystopian", "read": True, "rating": 5,
#      "available": True},
#     {"title": "To Kill a Mockingbird", "author": "Harper Lee", "year": 1960, "genre": "Fiction", "read": True,
#      "rating": 5, "available": True},
#     {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "year": 1925, "genre": "Classic", "read": False,
#      "rating": None, "available": True},
#     {"title": "Pride and Prejudice", "author": "Jane Austen", "year": 1813, "genre": "Romance", "read": True,
#      "rating": 5, "available": True},
#     {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "year": 1951, "genre": "Fiction", "read": False,
#      "rating": None, "available": True},
#     {"title": "The Alchemist", "author": "Paulo Coelho", "year": 1988, "genre": "Adventure", "read": True, "rating": 4,
#      "available": True},
#     {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "year": 1997, "genre": "Fantasy",
#      "read": True, "rating": 5, "available": True},
#     {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien", "year": 1954, "genre": "Fantasy", "read": False,
#      "rating": None, "available": True},
#     {"title": "The Da Vinci Code", "author": "Dan Brown", "year": 2003, "genre": "Thriller", "read": True, "rating": 4,
#      "available": True},
#     {"title": "The Hunger Games", "author": "Suzanne Collins", "year": 2008, "genre": "Dystopian", "read": False,
#      "rating": None, "available": True},
#     {"title": "Think and Grow Rich", "author": "Napoleon Hill", "year": 1937, "genre": "Self-help", "read": True,
#      "rating": 4, "available": True},
#     {"title": "Rich Dad Poor Dad", "author": "Robert Kiyosaki", "year": 1997, "genre": "Finance", "read": True,
#      "rating": 5, "available": True},
#     {"title": "Atomic Habits", "author": "James Clear", "year": 2018, "genre": "Self-help", "read": True, "rating": 5,
#      "available": True},
#     {"title": "Deep Work", "author": "Cal Newport", "year": 2016, "genre": "Productivity", "read": False,
#      "rating": None, "available": True},
#     {"title": "The Subtle Art of Not Giving a F*ck", "author": "Mark Manson", "year": 2016, "genre": "Self-help",
#      "read": True, "rating": 4, "available": True},
#     {"title": "The Hobbit", "author": "J.R.R. Tolkien", "year": 1937, "genre": "Fantasy", "read": True, "rating": 5,
#      "available": True},
#     {"title": "1984", "author": "George Orwell", "year": 1949, "genre": "Dystopian", "read": False, "rating": None,
#      "available": True},
#     {"title": "Dune", "author": "Frank Herbert", "year": 1965, "genre": "Science Fiction", "read": True, "rating": 4,
#      "available": True},
# ]

library = []
